from pathlib import Path
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
REPORTS_DIR = ROOT / "reports"

OUTPUT = REPORTS_DIR / "cleaning_log.csv"


def main():
    rows = [
        {
            "dataset": "Identity",
            "issue_area": "Exact duplicates",
            "action": "Removed exact duplicate rows",
            "method": "Kept one copy of identical records",
            "reason": "Prevent duplicate identity records from affecting downstream joins and counts",
            "evidence": "identity_cleaning_summary.csv",
            "result": "90 exact duplicate rows removed; 3000 cleaned rows",
        },
        {
            "dataset": "Identity",
            "issue_area": "User ID",
            "action": "Canonicalized user IDs",
            "method": "Normalized equivalent textual representations",
            "reason": "Create a consistent identity join key",
            "evidence": "identity_cleaning_summary.csv",
            "result": "0 invalid user IDs after cleaning",
        },
        {
            "dataset": "Identity",
            "issue_area": "Department",
            "action": "Standardized department values",
            "method": "Explicit mapping of known equivalent variants",
            "reason": "Avoid treating equivalent department names as separate categories",
            "evidence": "identity_cleaning_summary.csv",
            "result": "0 unmapped departments",
        },
        {
            "dataset": "Identity",
            "issue_area": "Status",
            "action": "Standardized identity status",
            "method": "Mapped known equivalent status representations to canonical states",
            "reason": "Create consistent employment/account lifecycle categories",
            "evidence": "identity_cleaning_summary.csv",
            "result": "0 unmapped statuses",
        },
        {
            "dataset": "Identity",
            "issue_area": "Hostname",
            "action": "Canonicalized hostnames",
            "method": "Trimmed, uppercased, replaced underscores with hyphens, removed .corp.local",
            "reason": "Improve reliable hostname-based joins",
            "evidence": "identity_cleaning_summary.csv",
            "result": "0 invalid hostnames after cleaning",
        },
        {
            "dataset": "Identity",
            "issue_area": "Dates",
            "action": "Parsed and validated hire/termination dates",
            "method": "Parsed supported date representations and flagged semantic inconsistencies",
            "reason": "Provide reliable dates without fabricating missing values",
            "evidence": "identity_cleaning_summary.csv",
            "result": "0 invalid hire dates; 0 invalid termination dates; 66 terminated-like records missing termination date flagged",
        },
        {
            "dataset": "IAM",
            "issue_area": "Exact duplicates",
            "action": "Removed exact duplicate rows",
            "method": "Kept one copy of identical records",
            "reason": "Prevent duplicate IAM events from distorting event counts",
            "evidence": "iam_cleaning_summary.csv",
            "result": "500 exact duplicate rows removed; 20000 cleaned rows",
        },
        {
            "dataset": "IAM",
            "issue_area": "User ID and department",
            "action": "Standardized identity fields",
            "method": "Applied canonical user ID and department mappings",
            "reason": "Ensure consistent identity integration",
            "evidence": "iam_cleaning_summary.csv",
            "result": "0 invalid user IDs; 0 unmapped departments",
        },
        {
            "dataset": "IAM",
            "issue_area": "Event type",
            "action": "Standardized event types",
            "method": "Mapped known equivalent authentication and access-event variants",
            "reason": "Create consistent event categories for analytics",
            "evidence": "iam_cleaning_summary.csv",
            "result": "0 unmapped event types",
        },
        {
            "dataset": "IAM",
            "issue_area": "MFA",
            "action": "Standardized MFA values",
            "method": "Converted True/False, Y/N, yes/no and 1/0 representations to boolean values",
            "reason": "Create a consistent analytical flag",
            "evidence": "iam_cleaning_summary.csv",
            "result": "0 invalid MFA values",
        },
        {
            "dataset": "IAM",
            "issue_area": "Timestamp",
            "action": "Parsed and validated timestamps",
            "method": "Parsed supported timestamp representations; retained unparseable values as invalid",
            "reason": "Avoid inventing event times",
            "evidence": "iam_cleaning_summary.csv",
            "result": "4395 invalid timestamps identified",
        },
        {
            "dataset": "IAM",
            "issue_area": "Source IP",
            "action": "Validated source IP addresses",
            "method": "Validated values using IP address parsing",
            "reason": "Prevent malformed IP addresses from being used as valid network indicators",
            "evidence": "iam_cleaning_summary.csv",
            "result": "10117 invalid source IP values identified",
        },
        {
            "dataset": "IAM",
            "issue_area": "Risk score",
            "action": "Separated numeric, categorical, missing and invalid risk values",
            "method": "Validated numeric scores against 0–100 and retained categorical risk labels separately",
            "reason": "Avoid fabricating numeric scores from unsupported categorical values",
            "evidence": "iam_cleaning_summary.csv",
            "result": "2607 out-of-range values; 1353 categorical values; 1037 missing values",
        },
        {
            "dataset": "Endpoint",
            "issue_area": "Exact duplicates",
            "action": "Removed exact duplicate rows",
            "method": "Kept one copy of identical records",
            "reason": "Prevent duplicate alerts from distorting security metrics",
            "evidence": "endpoint_cleaning_summary.csv",
            "result": "240 exact duplicate rows removed; 8000 cleaned rows",
        },
        {
            "dataset": "Endpoint",
            "issue_area": "Severity",
            "action": "Standardized severity",
            "method": "Mapped known variants to Critical, High, Medium and Low",
            "reason": "Enable consistent severity analysis",
            "evidence": "endpoint_cleaning_summary.csv",
            "result": "0 unmapped severity values",
        },
        {
            "dataset": "Endpoint",
            "issue_area": "Status",
            "action": "Standardized alert lifecycle status",
            "method": "Mapped equivalent lifecycle representations to canonical statuses",
            "reason": "Enable consistent alert lifecycle analysis",
            "evidence": "endpoint_cleaning_summary.csv",
            "result": "0 unmapped status values",
        },
        {
            "dataset": "Endpoint",
            "issue_area": "Device criticality",
            "action": "Standardized device criticality",
            "method": "Mapped known variants to Critical, High, Medium and Low",
            "reason": "Enable consistent asset-risk analysis",
            "evidence": "endpoint_cleaning_summary.csv",
            "result": "0 unmapped device criticality values",
        },
        {
            "dataset": "Endpoint",
            "issue_area": "Timestamps",
            "action": "Parsed detected and resolved timestamps",
            "method": "Parsed supported representations and retained validation results",
            "reason": "Provide reliable alert lifecycle timestamps",
            "evidence": "endpoint_cleaning_summary.csv",
            "result": "0 invalid detected timestamps; 0 invalid resolved timestamps",
        },
        {
            "dataset": "Endpoint",
            "issue_area": "Chronology",
            "action": "Flagged timestamp chronology anomalies",
            "method": "Did not swap or fabricate timestamps",
            "reason": "Preserve source chronology and avoid introducing unsupported values",
            "evidence": "endpoint_cleaning_summary.csv",
            "result": "263 chronology issues flagged",
        },
        {
            "dataset": "Endpoint",
            "issue_area": "SHA-256",
            "action": "Validated SHA-256 hashes",
            "method": "Required a valid 64-character hexadecimal representation",
            "reason": "Prevent malformed hashes from being treated as valid indicators",
            "evidence": "endpoint_cleaning_summary.csv",
            "result": "799 invalid SHA-256 values identified",
        },
        {
            "dataset": "Firewall",
            "issue_area": "Exact duplicates",
            "action": "Removed exact duplicate rows",
            "method": "Kept one copy of identical records",
            "reason": "Prevent duplicate network logs from distorting traffic metrics",
            "evidence": "firewall_cleaning_summary.csv",
            "result": "600 exact duplicate rows removed; 30000 cleaned rows",
        },
        {
            "dataset": "Firewall",
            "issue_area": "Timestamp",
            "action": "Parsed and validated timestamps",
            "method": "Parsed supported representations and retained invalid values as invalid",
            "reason": "Avoid fabricating network event times",
            "evidence": "firewall_cleaning_summary.csv",
            "result": "2986 invalid timestamps after cleaning",
        },
        {
            "dataset": "Firewall",
            "issue_area": "IP addresses",
            "action": "Validated source and destination IPs",
            "method": "Applied IP address validation",
            "reason": "Prevent malformed network indicators from entering analytics as valid IPs",
            "evidence": "firewall_cleaning_summary.csv",
            "result": "13471 invalid source IPs; 12756 invalid destination IPs",
        },
        {
            "dataset": "Firewall",
            "issue_area": "Ports",
            "action": "Validated source and destination ports",
            "method": "Accepted only values from 1 through 65535",
            "reason": "Enforce the valid network port domain",
            "evidence": "firewall_cleaning_summary.csv",
            "result": "3608 invalid source ports; 3556 invalid destination ports",
        },
        {
            "dataset": "Firewall",
            "issue_area": "Byte counts",
            "action": "Parsed and validated byte values",
            "method": "Converted supported numeric/unit representations and rejected negative or invalid values",
            "reason": "Prevent invalid traffic-volume measurements",
            "evidence": "firewall_cleaning_summary.csv",
            "result": "5101 invalid bytes-sent values; 5086 invalid bytes-received values",
        },
        {
            "dataset": "Firewall",
            "issue_area": "Protocol and action",
            "action": "Standardized categorical network fields",
            "method": "Mapped equivalent protocol and firewall-action representations",
            "reason": "Enable consistent network traffic analysis",
            "evidence": "firewall_cleaning_summary.csv",
            "result": "Canonical analytical fields generated",
        },
        {
            "dataset": "Firewall",
            "issue_area": "Threat flag",
            "action": "Standardized threat flag",
            "method": "Converted True/False, Y/N, yes/no and 1/0 representations to boolean values",
            "reason": "Create a consistent security indicator",
            "evidence": "firewall_cleaning_summary.csv",
            "result": "Canonical threat flag generated",
        },
        {
            "dataset": "Cross-dataset",
            "issue_area": "Join keys",
            "action": "Canonicalized user IDs and hostnames before joins",
            "method": "Applied the same normalization rules across datasets",
            "reason": "Reduce false unmatched records caused by formatting differences",
            "evidence": "cleaned_join_validation_summary.csv",
            "result": "IAM→Identity and Endpoint→Identity user ID joins fully matched",
        },
        {
            "dataset": "Cross-dataset",
            "issue_area": "Source coverage",
            "action": "Retained unmatched hostname records",
            "method": "Reported unmatched records instead of creating synthetic identity records",
            "reason": "Avoid fabricating source data",
            "evidence": "cleaned_join_validation_summary.csv",
            "result": "482 Endpoint and 1578 Firewall hostname records remain unmatched",
        },
    ]

    result = pd.DataFrame(rows)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(OUTPUT, index=False)

    print(f"Created: {OUTPUT}")
    print(f"Rows logged: {len(result)}")


if __name__ == "__main__":
    main()